perf tests: Fix compilation for mmap-thread-lookup on i386
Fixing following errors on i386 build:

tests/mmap-thread-lookup.c:192:11: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]

  We cast from pointer to integer, so we need to make sure
  it's the same size. The "unsigned long" type has pointer
  size on both 32/64 archs.

tests/mmap-thread-lookup.c:200:3: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘u64’ [-Werror=format]

  Using standard PRIx64 to display u64 value.

Cc: Corey Ashford <cjashfor@linux.vnet.ibm.com>
Cc: David Ahern <dsahern@gmail.com>
Cc: Frederic Weisbecker <fweisbec@gmail.com>
Cc: Ingo Molnar <mingo@kernel.org>
Cc: Namhyung Kim <namhyung@kernel.org>
Cc: Paul Mackerras <paulus@samba.org>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Link: TODO send and get link
Signed-off-by: Jiri Olsa <jolsa@redhat.com>