perf tools: Renaming 'time' variable in perf_time_to_tsc due to name shadowing error
The perf compilation fails with following error:
      ...
      CC arch/x86/util/tsc.o
  arch/x86/util/tsc.c: In function ‘perf_time_to_tsc’:
  arch/x86/util/tsc.c:13:6: error: declaration of ‘time’ shadows a global declaration [-Werror=shadow]
  cc1: all warnings being treated as errors

Renaming the 'time' variable to prevent this.

Signed-off-by: Jiri Olsa <jolsa@redhat.com>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: Corey Ashford <cjashfor@linux.vnet.ibm.com>
Cc: Ingo Molnar <mingo@elte.hu>
Cc: Paul Mackerras <paulus@samba.org>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: David Ahern <dsahern@gmail.com>