libbpf: Add missing install_headers for bpftool bootstrap target
We can't no longer build bootstrap bpftool from perf, because it's
missing the headers:

  $ make BUILD_BPF_SKEL=1
  ...
  gen.c: In function ‘codegen_datasecs’:
  gen.c:214:10: warning: implicit declaration of function ‘btf__type_cnt’
  [-Wimplicit-function-declaration]
    214 |  int n = btf__type_cnt(btf);
        |          ^~~~~~~~~~~~~
  ...

The reason is recent change (f012ade10b34) that switched from
including libbpf directly to having them installed first.

The bootstrap target builds its own libbpf which does not invoke
install_headers target, adding that.

This is not a problem in normal bpftool build, because it invokes
standard libbpf build first with the install_headers target.

Fixes: f012ade10b34 ("bpftool: Install libbpf headers instead of including the dir")
Signed-off-by: Jiri Olsa <jolsa@kernel.org>