perf probe: Add warning message for invalid kprobe_events event name
This improves the error message so that the user can know an event name
error before writing new events to kprobe_events interface.

E.g.
   ======
   # perf probe -x /lib64/libc-2.25.so malloc_get_state*
   Internal error: "malloc_get_state@GLIBC_2" is an invalid event name for the /sys/kernel/debug/tracing/kprobe_events interface.
     Error: Failed to add events.
   ======

Signed-off-by: Masami Hiramatsu <mhiramat@kernel.org>
Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Cc: bhargavb <bhargavaramudu@gmail.com>
Cc: Paul Clarke <pc@us.ibm.com>
Cc: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
Link: http://lkml.kernel.org/r/151263118520.13843.9962959734014217698.stgit@devbox
[ Use 'invalid event name for ...' instead of just 'wrong event name' ]
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>