perf stat: Fix recort_usage typo
Markus reported gcc 6 complains when compiling perf stat command:

  builtin-stat.c:1591:27: error: ‘recort_usage’ defined but not used
  [-Werror=unused-const-variable]
   static const char * const recort_usage[] = {
                             ^~~~~~~~~~~~
I fixed the typo and realized we already export record_usage,
so I also prefixed it with stat (and included report_usage).

Reported-by: Markus Trippelsdorf <markus@trippelsdorf.de>
Link: http://lkml.kernel.org/n/tip-3c3vkc6bejfsuxxgkcwxllsc@git.kernel.org
Signed-off-by: Jiri Olsa <jolsa@kernel.org>